### ISSUE TITLE
Does this code implement the connectivity computations in Adcroft 2013?

### ISSUE THREAD

**Issue by ezaron** [nikizadehgfdl/ocean_model_topog_generator#6]
Hi Niki:
I was studying your code and considering to use it to generate MOM6 topography. One aspect of the Adcroft 2013 paper was his treatment of connectivity, illustrated in his Fig 5-6, for example. Did you implement that aspect of his algorithm in your ocean_model_topog_generator?

-Ed Zaron

**Comment by nikizadehgfdl** [comment]
No. This tool only implements only that part of Adcroft et.al.  algorithm to remap a source topography dataset (like GEBCO) to a 2D ocean model grid. As it is , it only generates depth and roughness on the model grid.
